### ISSUE TITLE
Switch away from js generated everything

### ISSUE THREAD

**Issue by est31** [steveklabnik/rustdoc#1]
I see that this rewrite uses ember. That's pretty sad as it means that when you open a link, a non trivial amount of javascript has to run before the browser can even start to render the page. I don't demand a js free mode (as in, all features working with js disabled), just ember is using js for a purpose that user agent scripting wasn't actually designed for, and therefore the end result sucks pretty bad.

As a negative example, I just look at crates.io, which has heavy use of js modifying the DOM as well, and this leads to weird bugs like https://github.com/rust-lang/crates.io/issues/306, as well as laggy behaviour in general.

I know this is right now a bit hand wavery, but I wanted to point this out early in the process where a switch is hopefully still very cheap.

**Comment by est31** [comment]
*hmmm* from IRC @quietmisdreavus told me that the goal was to get web developers to work on the tool. This is in fact a great idea! Will it be the default output mode of `cargo doc` though?

**Comment by steveklabnik** [comment]
This is far too early to have real discussions about this, and it shouldn't be in an issue anyway.

Yes, the idea is that you can have a non-JS renderer if you want to.
