### ISSUE TITLE
Support non-module items: backend

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#121]
Once I work the bugs out of https://github.com/steveklabnik/rustdoc/pull/108, it'll be time to support the other kinds of items.

Fundamentally, what needs to happen is with [this line](https://github.com/steveklabnik/rustdoc/blob/782fd7f8c5e6cef878183c52121ef5414872e0c5/src/json/mod.rs#L52); instead of `_ => continue`, it should have every [`DefKind`](https://docs.rs/rls-analysis/0.6.5/rls_analysis/enum.DefKind.html).

- [ ] Enum
- [ ] Tuple
- [ ] Struct
- [ ] Union
- [ ] Trait
- [ ] Function
- [ ] Method
- [ ] Macro
- [ ] Mod
- [ ] Type
- [ ] Local
- [ ] Static
- [ ] Const
- [ ] Field

I am not actually sure about `Local`, as I'd imagine local items don't need to be documented.

**Comment by mgattozzi** [comment]
We just finished what #108 was trying to do with #171. Time to start working on this issue now. Definitely a good place to start if you're new to the project/have some Rust experience. Willing to help mentor as well for these.

**Comment by projektir** [comment]
I'm assuming `ty` stands for "type"?

How does one determine what should be returned for every DefKind here? There's more to it than strings like "module", "modules", right?

**Comment by steveklabnik** [comment]
Yeah, `ty` is type.

> How does one determine what should be returned for every DefKind here? There's more to it than strings like "module", "modules", right?

For the backend, it needs to be in two places; https://github.com/steveklabnik/rustdoc/blob/48794bde699955b38c4ea849d915d1e4cfd510c2/src/json/mod.rs#L60 and https://github.com/steveklabnik/rustdoc/blob/48794bde699955b38c4ea849d915d1e4cfd510c2/src/json/mod.rs#L88 note the small differences. That's because....

for the frontend, https://github.com/steveklabnik/rustdoc/tree/48794bde699955b38c4ea849d915d1e4cfd510c2/frontend/app/models 

* https://github.com/steveklabnik/rustdoc/blob/48794bde699955b38c4ea849d915d1e4cfd510c2/frontend/app/models/crate.js#L5 for the crate itself, and a new model like https://github.com/steveklabnik/rustdoc/blob/48794bde699955b38c4ea849d915d1e4cfd510c2/frontend/app/models/module.js; note while we support structs on the backend, we don't on the front-end yet, so these things can be landed separately!

Part of this is because full support on the front-end is going to be a little tricky; https://github.com/steveklabnik/rustdoc/blob/48794bde699955b38c4ea849d915d1e4cfd510c2/frontend/app/routes/modules.js is what we had going for modules, but the other types will need special URLs too, I have to tinker with it to figure out exactly what's up yet.
