### ISSUE TITLE
Finish docs on existing rustdoc

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#124]
I'm filing this issue here rather than on rust-lang/rust because it's more relevant to people on this repo, but https://github.com/rust-lang/rust/tree/master/src/doc/rustdoc is the docs for the old rustdoc, and we should fill it out so that we can determine if we're compatible with the older rustdoc, and how much.

Filling these out is important:

- [x] What is rustdoc?
- [x] Command-line arguments
- [x] In-source directives
- [x] Documentation tests
- [x] Plugins
- [x] Passes

Marking this as "easy" because it mostly requires reading code, not writing it. I'm happy to elaborate a bit more about the details here if needed!

**Comment by lukaramu** [comment]
cc rust-lang/rust#42322

**Comment by gnzlbg** [comment]
This documentation misses actually the syntax allowed in documentation comments. 

Ok, it does mention markdown, but the current rustdoc supports crosslinking methods, functions, traits, etc. It would be nice to document all of this because many projects are using these.

**Comment by steveklabnik** [comment]
> but the current rustdoc supports crosslinking methods, functions, traits,

Since when?

**Comment by gnzlbg** [comment]
Since as far as I can remember: https://rust-lang-nursery.github.io/stdsimd/x86_64/stdsimd/vendor/constant._MM_EXCEPT_DENORM.html 

There is a `See _mm_setcsr` in that page, that is a cross link. You can have a function link against trait methods, struct data members, enum variants, etc. It seems to rely on the adhoc way in which rustdoc generates lables and the html pages for the items, but... it works, and many projects use this.

**Comment by steveklabnik** [comment]
Right, but that's just markdown. Look at the source:

    /// See [`_mm_setcsr`](fn._mm_setcsr.html)

That's a manual link. Just markdown.

**Comment by gnzlbg** [comment]
Ah yes, sure. I was just saying that being able to create these links depends on how rustdoc currently creates the files (e.g. that it puts functions into `fn.{{function_name}}.html` files) so we might as well document that.

**Comment by steveklabnik** [comment]
This is effectively complete for our purposes here. Obviously the rustdoc book can be improved, but that's not a thing to track in this repo.
