### ISSUE TITLE
Flags: help

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#126]
This issue is part of https://github.com/steveklabnik/rustdoc/issues/125

## `-h`/`--help`: help

Using this flag looks like this:

```bash
$ rustdoc -h
$ rustdoc --help
```

This will show `rustdoc`'s built-in help, which largely consists of
a list of possible command-line flags.

Some of `rustdoc`'s flags are unstable; this page only shows stable
options, `--help` will show them all.

----------------------------------------------------

Should we keep this flag or not?

**Comment by steveklabnik** [comment]
I can't imagine we don't keep this.

Maybe we want a subcommand now though?

**Comment by euclio** [comment]
Clap automatically provides both.

**Comment by mgattozzi** [comment]
Yeah we can pretty much close this one and #127 because of clap.

**Comment by steveklabnik** [comment]
Nice!
