### ISSUE TITLE
Flags: verbose

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#128]
This issue is part of https://github.com/steveklabnik/rustdoc/issues/125

## `-v`/`--verbose`: more verbose output

Using this flag looks like this:

```bash
$ rustdoc -v src/lib.rs
$ rustdoc --verbose src/lib.rs
```

This enables "verbose mode", which means that more information will be written
to standard out. What is written depends on the other flags you've passed in.
For example, with `--version`:

```text
$ rustdoc --verbose --version
rustdoc 1.17.0 (56124baa9 2017-04-24)
binary: rustdoc
commit-hash: hash
commit-date: date
host: host-triple
release: 1.17.0
LLVM version: 3.9
```

----------------------------------------------------

Should we keep this flag or not?

**Comment by steveklabnik** [comment]
This seems like a pretty obvious thing to keep. Possibly we should have a quiet flag too!

**Comment by euclio** [comment]
If a user passed the verbose flag, would we want to forego the spinners and just print all messages to stdout?

**Comment by steveklabnik** [comment]
Yeah, dropping the spinners and printing out *some* form of logs seems 👍
