### ISSUE TITLE
Flag: output path

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#131]
This issue is part of https://github.com/steveklabnik/rustdoc/issues/125

## `-o`/`--output`: output path

Using this flag looks like this:

```bash
$ rustdoc src/lib.rs -o target\\doc
$ rustdoc src/lib.rs --output target\\doc
```

By default, `rustdoc`'s output appears in a directory named `doc` in
the current working directory. With this flag, it will place all output
into the directory you specify.

----------------------------------------------------

Should we keep this flag or not?

**Comment by steveklabnik** [comment]
This seems important to keep.

Our default is different than this one; we assume Cargo and write to `target/doc`. Today's Cargo passes this flag to rustdoc to write to that location, and rustdoc defaults to `./doc`.

**Comment by euclio** [comment]
Looks like `-o` is already claimed by `rustdoc build --open`.

**Comment by mgattozzi** [comment]
Maybe just leave --open as a long flag only and have -o/--output be the other flags? Conventionally for many compilers and programs -o is used for output directories

**Comment by steveklabnik** [comment]
Yes, we should leave `--open` as a long flag only, and take `-o` for this.

**Comment by hjr3** [comment]
There is some inconsistency with `manifest-path` having _-path_ and `--output` not having _-path_. Also, https://github.com/steveklabnik/rustdoc/issues/133 specifies `--library-path`.
