### ISSUE TITLE
Flag: tests

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#140]
This issue is part of https://github.com/steveklabnik/rustdoc/issues/125

## `--test`: run code examples as tests

Using this flag looks like this:

```bash
$ rustdoc src/lib.rs --test
```

This flag will run your code examples as tests. For more, see [the chapter
on documentation tests](documentation-tests.html).

See also `--test-args`.

----------------------------------------------------

Should we keep this flag or not?

**Comment by steveklabnik** [comment]
Very important!

**Comment by killercup** [comment]
[This is also used on markdown files in the wild](https://github.com/sfackler/rust-native-tls/blob/89be7b1b96eb5d09d9741bb02fe26217e1e40fbb/.travis.yml#L15)

**Comment by euclio** [comment]
I started working on this, but it's blocked by https://github.com/nrc/rls-analysis/issues/99
