### ISSUE TITLE
Run Appveyor/Travis on a daily basis

### ISSUE THREAD

**Issue by mgattozzi** [steveklabnik/rustdoc#158]
Travis and Appveyor both have the ability to schedule builds. Since we use nightly it would be great to set them up to run nightly as well to check for possible breakage from newer versions of Rust.

**Comment by steveklabnik** [comment]
👍

**Comment by mgattozzi** [comment]
@steveklabnik since you're the only one with access to those you'll have to be the one to set it up

**Comment by steveklabnik** [comment]
I've updated travis to do it; i had to email appveyor support to ask about recurring builds, we'll see what they say!

**Comment by steveklabnik** [comment]
appveyor is now turned on too!

**Comment by mgattozzi** [comment]
Yay!
