### ISSUE TITLE
Improve CI setup

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#17]
In https://github.com/steveklabnik/rustdoc/issues/12 we added Travis. It only currently runs `cargo test`/`npm run test`.

We should also:

- Run rustfmt, and fail if its output isn't correct
- Run `npm run eslint` and fail if it fails

**Comment by sivakumar-kailasam** [comment]
@steveklabnik eslint tests are run as a part of the ember test suite, so running `ember test` should suffice.

**Comment by steveklabnik** [comment]
@sivakumar-kailasam ah thanks for that info! That's great.
