### ISSUE TITLE
Better describe the "why" of this project

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#172]
Explaining *how* and *why* this is different/better than the current rustdoc is something we do poorly.

https://internals.rust-lang.org/t/the-rustdoc-redux/5542 has some of this kind of thing, adapting it to some sort of document in the repo would be a good idea.

**Comment by mgattozzi** [comment]
@steveklabnik wasn't this closed by #172?

**Comment by steveklabnik** [comment]
Yes!
