### ISSUE TITLE
Roadmap to feature parity with rustc's rustdoc

### ISSUE THREAD

**Issue by gnzlbg** [steveklabnik/rustdoc#184]
It would be nice to have a list of all the work that needs to be done for feature parity with rustc's rustdoc, and maybe to tag those issues accordingly. @steveklabnik 

There is an issue about flags, but we are going to need things like output as well.

**Comment by euclio** [comment]
I think this would be a good use case for GitHub milestones.

**Comment by steveklabnik** [comment]
Yes, I'm using milestones to track this stuff; I'll be updating them shortly.
