### ISSUE TITLE
Source links aren’t visible on small screens

### ISSUE THREAD

**Issue by rightfold** [steveklabnik/rustdoc#201]
If I try to go to the source of an item on a mobile phone, I can’t, because the source link is hidden. It does work on a large screen (such as that of a desktop computer).

**Comment by steveklabnik** [comment]
Could you re-file against http://github.com/rust-lang/rust/ please? This repo is for a re-write, which does not have source links at all, so I believe you're talking about current-existing rustdoc, and it tracks bugs over there. Thank you!

**Comment by rightfold** [comment]
Oh, I see. Thanks. :) I’ll post it there.
