### ISSUE TITLE
Red links feel like missing links to me

### ISSUE THREAD

**Issue by timClicks** [steveklabnik/rustdoc#226]
When I first encountered rustdoc, I was at a loss as to why so many links were marked as missing. Apparently I've been trained by Wikipedia/MediaWiki defaults to see red and infer missing page. It took me an embarrassingly long time to realize that they're perfectly clickable.

As an example, [structs are rendered in red](https://doc.rust-lang.org/stable/std/vec/#structs). So yeah, for several months while learning Rust I eagerly waited for Rust's docs to be updated with their struct definitions to be included in the build.

So this a trivial issue, but I thought it was worth pointing out for the sake of anyone else.

**Comment by mgattozzi** [comment]
@timClicks this is the rewrite for rustdoc. Just to be clear did you want it for this repo or the tool as it currently exists over on [rust-lang/rust](https://github.com/rust-lang/rust)?

**Comment by timClicks** [comment]
@mgattozzi Urgh. Sorry for the mixup. For the docs as rendered by rust-lang/rust.

**Comment by steveklabnik** [comment]
Yup! Please file this over there. Thanks :)

**Comment by mgattozzi** [comment]
No problem @timClicks you're not the only one to have filed over here by accident :)
