### ISSUE TITLE
Broken jsonapi.org link in readme

### ISSUE THREAD

**Issue by dtolnay** [steveklabnik/rustdoc#227]
The linked https://jsonapi.org/ is serving a certificate that is not valid for jsonapi.org. Their GitHub repo looks like it links to http://jsonapi.org/.

**Comment by steveklabnik** [comment]
ah thanks; yeah, we use github pages so we can't https

**Comment by dtolnay** [comment]
CloudFlare supports https for github pages. We use it for https://serde.rs.

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
