### ISSUE TITLE
Rust cfg_attr style code blocks

### ISSUE THREAD

**Issue by kbknapp** [steveklabnik/rustdoc#235]
Forgive me if this has been addressed, or isn't the proper place, but is there any way to use Rust style cfg statements in the code blocks?

For example, right now I have multiple code blocks I want to ignore on non-unix systems, but use doc tests for unix systems.

So right now my doc comments look like this:

```
/// Some comments
#[cfg_attr(not(unix), doc = " ```ignore")]
#[cfg_attr(unix, doc = " ```")]
/// // code
/// ```
```

Which is less than ideal (although it works) and has created a few issues where doc tests were either not functioning correctly, or incorrectly ignored.

It'd be super cool if I could something like

```
/// Some comments
/// ```cfg_attr(not(unix), ignore)
/// // code
/// ```
```

**Comment by steveklabnik** [comment]
Hey, sorry for taking so long!

This isn't the right place to put this; as this is a re-write of rustdoc without a real frontend yet! "how do I use" questions are best asked on users.rust-lang.org. Thanks/sorry!

**Comment by kbknapp** [comment]
No worries, thanks Steve! :+1:
