### ISSUE TITLE
Improve TUI

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#37]
https://github.com/mitsuhiko/indicatif would be much nicer than the current

    println!("Processing...");

**Comment by mgattozzi** [comment]
Is there something you had in mind with what you want it to do?
Like a spinner while processing at each stage or a bar for x files and updating as they're processed?

**Comment by steveklabnik** [comment]
@mgattozzi I'm open to suggestions!

I think I like spinners because progress bars are really hard to determine, like, we don't have a good way to measure percentage done.

**Comment by mgattozzi** [comment]
That's why I was thinking spinners as well. I just wasn't sure if there was some way we could count things and would want a bar vs just showing things are happening.

**Comment by steveklabnik** [comment]
With https://github.com/steveklabnik/rustdoc/pull/31 merged, we now have one nested output:

```text
generating JSON...generating save analysis data...done.
loading save analysis data...done.
done.
copying assets...done.
```

Hopefully this can address that in some form!
