### ISSUE TITLE
Get rid of Box<Error>

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#46]
We should have our own error type instead.

**Comment by mgattozzi** [comment]
Do we want to consider using `error-chain` at all or would it be better to make a custom error instead?

**Comment by steveklabnik** [comment]
I personally have never used `error-chain`; I'm not sure. I should probably try each way and then compare; that is a lot of burden to put on someone though :(

**Comment by mgattozzi** [comment]
I've used error-chain pretty extensively. I could whip something up with that if you'd like.

**Comment by steveklabnik** [comment]
Sure thing!

I'm working on https://github.com/steveklabnik/rustdoc/issues/11 right now and it's adding way, way more functions that return Result, so if it can truly save a lot of boilerplate, that'd be 👍
