### ISSUE TITLE
Cannot find crate if crate name is different from package name

### ISSUE THREAD

**Issue by euclio** [steveklabnik/rustdoc#51]
I have a crate where the package name is `feo-boy`, but the crate name is `feo_boy`. `rustdoc` fails to find the root crate in this case. Additionally, it returns the error message `Application error: Crate not found: "example"`, because of the hard-coded error.

**Comment by steveklabnik** [comment]
Ah ha, so https://github.com/steveklabnik/rustdoc/pull/42 didn't go far enough, it seems...

**Comment by hjr3** [comment]
I tried to recreate this and could not. Good call out on missing the error message. I fixed this originally and overlooked it when I switched to shelling out.

My attempt at a repro:

```
herman@titan ~/projects/rustdoc !! cat ../feo-boy/Cargo.toml
[package]
name = "feo_boy"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]
herman@titan ~/projects/rustdoc !! cargo run -- --manifest-path=../feo-boy build
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/rustdoc --manifest-path=../feo-boy build`
  Generating save analysis data: Done
  Loading save analysis data: Done
  Generating JSON: Done
  Copying Assets: Done
herman@titan ~/projects/rustdoc !! git rev-parse HEAD
ba09842fc9eb038aeefca8a40cd15f9ed8cbaf37
```

**Comment by euclio** [comment]
The package name should be `feo-boy`, not `feo_boy`. I think the mismatch comes from crate name vs. package name.

**Comment by hjr3** [comment]
I put in a fix. I would like to write tests for this code. The code relies on the file system. My thoughts are to do what cargo with the `tests/cargotest` directory. I expect that to expand into building mock crates in that directory for even more test coverage. Are there any concerns with this approach?

**Comment by euclio** [comment]
I've written an approach to integration testing in #61. It might only be necessary to write tests that the analysis is generated correctly for a cargo project.

**Comment by hjr3** [comment]
So @steveklabnik told me in https://github.com/steveklabnik/rustdoc/pull/62#issuecomment-317452178 that the crate name is the target name in Cargo.toml (this makes total sense in hindsight).

My question now is how do we figure out which target to use? There can be only one lib target, so that is easy. I imagine people will want to run rustdoc on bin targets, which there can be multiple of. 

So given something like below, which one are we to pick?

```toml
[package]
name = "example"

[lib]
name = "foo"
path = "src/lib.rs"

[[bin]]
name = "bar"
path = "src/bar.rs"

[[bin]]
name = "baz"
path = "src/baz.rs"
```

**Comment by euclio** [comment]
Is there a reason we can't document all of them?

**Comment by hjr3** [comment]
@euclio we could. that would require us to change the structure of `data.json` to allow an array of roots or use the target name for each json file.

**Comment by euclio** [comment]
Got it. Having an array seems more flexible, but both seem reasonable. The
larger question is whether we are trying to emulate `rustdoc` or `cargo
doc`'s behavior.

**Comment by steveklabnik** [comment]
>  I imagine people will want to run rustdoc on bin targets, which there can be multiple of.

Current rustdoc cannot do this, so I think not supporting it for now would be acceptable.
