### ISSUE TITLE
Allow pluggable frontend

### ISSUE THREAD

**Issue by mgattozzi** [steveklabnik/rustdoc#52]
Currently the way `rustdoc` works is by dynamically compiling whatever is in `frontend/dist` into the binary. This is great since that means we can just distribute `rustdoc` and not need a dependency on `ember` However, this means that right now `rustdoc` only uses ember for it's frontend. People have expressed interest in being able to have a plug and play aspect to how it's output. How would we go about solving this issue, while allowing rustdoc to not have to be built in a two stage fashion?

**Comment by steveklabnik** [comment]
Marking this as quest because there's certainly a lot of options here.

**Comment by hardvain** [comment]
@steveklabnik @mgattozzi I am just wondering do we really need a ember (SPA) here. I think it will help if we first determine what features do we really need in the rust doc and then decide if we need a SPA?  If not, we can achieve a lot with the plain static html,js,css files itself. Besides we dont need to worry about SEO if we dont use a SPA and entry barrier for newbies will also be low. Irrespective of whether we use a SPA or not, will it help to have the frontend itself in a separate repo? This will also prevent us from accidentally coupling frontend and backend. But it has the downside of generating a final binary from the build of two repos.

**Comment by steveklabnik** [comment]
>  I am just wondering do we really need a ember (SPA) here

This is a decision we made a long time ago; we're not particularly interested in litigating it again. That internals thread would be the place to do so, but all of your points were raised in that thread. 😄

**Comment by mgattozzi** [comment]
Yeah all those were brought up there. I'd have to find the thread but it was hashed out quite extensively. The idea here is you whould just be able to have rustdoc build and work as a tool. We've decided to use ember for the tool officially, but we want people to be able to choose how they display things or make them more to their liking, maybe they want Angular or static files instead! We've done some work to just allow what we process to be output as JSON to then be used by anything. They can use rustdoc to parse all the documentation and then write another frontend to output stuff. We want to make it easy for people to choose because not everyone wants the same thing.

**Comment by euclio** [comment]
I've written a frontend that generates static files here: https://github.com/euclio/rustdoc-frontend.
