### ISSUE TITLE
Inline docdata::build_data

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#55]
In https://github.com/steveklabnik/rustdoc/pull/47, @jbcden raised some good points about `build_data` being awkward: https://github.com/steveklabnik/rustdoc/pull/47#discussion_r128135721

I've merged it, but this would still be a good refactoring.

https://github.com/steveklabnik/rustdoc/blob/master/src/lib.rs#L201-L242

**Comment by jbcden** [comment]
@steveklabnik I'd be happy to take a run at this. I'm still fairly new to Rust so I might need help at some point.

**Comment by steveklabnik** [comment]
@jbcden awesome! Please feel free to either open up a partial PR where we can discuss things or ping me on irc, whichever is more helpful to you, if you get stuck!

**Comment by jbcden** [comment]
@steveklabnik was there more work around this that you wanted or is this issue closed by https://github.com/steveklabnik/rustdoc/pull/57?

**Comment by steveklabnik** [comment]
It was! Thanks 😄
