### ISSUE TITLE
Improve build.rs to not add extra files

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#58]
In https://github.com/steveklabnik/rustdoc/commit/718768e2c8ddb51331e244f0a7655b952bb3217f, we added a `build.rs` to properly package up the assets.

The problem is, I just spent about two hours debugging a problem that boiled down to "hey steve had a `data.json` file lying inside of `frontend/dist` for some reason. So my code was writing out a `data.json`, only to immediately be overwritten by the old file. Ugh!

We can't do a literal whitelist because of the hashes, but maybe blacklisting other files isn't good... I dunno.

**Comment by mgattozzi** [comment]
Would it be possible to do it based off of suffix/prefix for now? If you removed the data.json did it work out fine? This seems similar to #53. Certain files/assets when included in the code seem to cause it to fail.

**Comment by mgattozzi** [comment]
There have been quite a few changes to build.rs recently. Is this still an issue? I'm guessing it is but better to be up to date on it.

**Comment by hjr3** [comment]
One of the things we did in cargo was to allow for glob syntax to work whitelist workspace members. See https://github.com/rust-lang/cargo/pull/3979. For rustdoc, we could do something like:

```rust
let whitelist = vec!["assets/*", "ember-fetch/*", "index.hml", "robots.txt"];
```

We would then find every file under `frontend/dist` and filter it against the whitelist.
