### ISSUE TITLE
Improve fetching of defs

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#70]
In https://github.com/steveklabnik/rustdoc/pull/66 we did a naive recursive fetching of all defs, but for large crates, this might blow the stack. In addition, it's all serial; we may want to investigate parallelizing it.

**Comment by DevOrc** [comment]
Hey! I am new to rust but looking to contibute! Did you have any idea or plan to do this or is it still up in the air?

**Comment by steveklabnik** [comment]
@DevOrc hey hey! I do not have any specifics yet; this ticket is basically "make https://github.com/steveklabnik/rustdoc/blob/master/src/lib.rs#L209-L227 better."

If you have any ideas, feel free to comment about them or whip up a PR, and we can discuss!

**Comment by fj** [comment]
@steveklabnik suggestion: you may want to link to a specific commit's instance of `src/lib.rs` — otherwise changes to this file overtime will invalidate your link.
