### ISSUE TITLE
Fix the "hilarious hard-coding"

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#8]
Right now, the hash of the frontend files is coded into the binary, so when we update the front end, it won't get picked up automatically.

To fix:

1. Instead of hardcoding, have it read the directory to determine the file names.
2. Modify the `Assets` struct to be able to handle a name as well as the contents. Possibly, this should instead be an `Asset` struct with name + contents, and the `Assets` struct could be a `Vec<Asset>`.
3. use these names when writing out the files.

* https://github.com/steveklabnik/rustdoc/blob/99685f23ea55af4dc641c953c1f9fc5df8235b46/src/main.rs#L42
* https://github.com/steveklabnik/rustdoc/blob/99685f23ea55af4dc641c953c1f9fc5df8235b46/src/main.rs#L249

**Comment by steveklabnik** [comment]
in https://github.com/steveklabnik/rustdoc/commit/1a18e54e2a4159346e09d801969bf12b00a8219b, I've done step 1 above. This helps a bit but is not a total solution.

The real solution to this problem is that `include_str` must take a string literal only. This means we have two options:

1. `build.rs`
2. procedural macros

The former is stable, but gross. The latter is nice, but unstable.

I'm going to consider this "good enough for now", and move it to the "everything but traits" milestone; it's a small wart on the "hello world" but there's not a ton that can be done right this moment.

**Comment by myrrlyn** [comment]
For what it's worth, I've just ~~finished~~ gotten working a `build.rs` script for a project of mine that can install template files from the source tree into folders obtained from the `appdirs` crate and also generate Rust modules that load those files at runtime. If I weren't about to head into the wilderness for a week I'd volunteer to get your build script running nicely here.

**Comment by steveklabnik** [comment]
@myrrlyn ah cool, thanks!

I think that this could be an extremely useful general crate; I'm imagining there are others with this exact problem.

**Comment by myrrlyn** [comment]
https://github.com/myrrlyn/assoc_files_rs

I have not included the second half of my description ("generate Rust modules to load the installed files"), as that was a very project-specific endeavour and I do not know how to generalize it at this time.

But this can be embedded in `build.rs` to shunt files to `~/.local/share/rustdoc/VERSION` (Linux), `~/Library/Application Support/rustdoc/VERSION` (macOS), or `%USERPROFILE%/AppData/Local/rustdoc/version` (Windows) conveniently with the `user_data![files, ...]` macro, or to wherever you like with the `install_files(&[files, ...], &target)` function, and runtime logic can access those paths with `user_data!()` or hardcoding the same path from the build script.

I have no idea how I'd go about making this a procedural macro, but I'll give it some thought over the next week and see if I can't come up with an abstract idea. Maybe decorate a variable with a `#[load_from(path)]` annotation that will install at compile time and load at runtime? I don't even know what's possible in that realm.

Hope this is at all useful to the problem you're facing.
