### ISSUE TITLE
get rid of nested item module

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/rustdoc#87]
We have https://github.com/steveklabnik/rustdoc/blob/master/src/item.rs#L1  which leads to https://github.com/steveklabnik/rustdoc/blob/master/src/lib.rs#L14

that first line should be removed, and the import adjusted, so it's just `item` and not `item::item`.

This is a very good first issue!

**Comment by mgattozzi** [comment]
Do you think we should tag issues like this with something like E-Easy and other things as E-Medium or E-Hard as well so that we can have newer contributors have a reference of where they might want to start?
