### ISSUE TITLE
Provide a subcommand to open the docs in the default browser

### ISSUE THREAD

**Issue by euclio** [steveklabnik/rustdoc#90]
Bikeshedding the name:`rustdoc open`, `rustdoc run`, `rustdoc build --open`

~This might be blocked on #40...?~

**Comment by mgattozzi** [comment]
With `rustup` the command is `rustup doc` to open the std docs in the default browser. However, a command like `rustdoc doc` doesn't seem like the right choice here. Personally I think `rustdoc open` would be best. As for #40 I don't think it blocks this. It's just a mac specific issue making it impossible to use rustdoc as is. We can still make a command that opens the docs in the browser.

**Comment by euclio** [comment]
I'll note that cargo currently has `cargo doc --open` as well. I agree that `rustdoc open` seems the most reasonable.

**Comment by steveklabnik** [comment]
It'd be

    rustdoc --manifest-path=example open

because the `--manifest-path` argument is to `rustdoc` not its subcommand.

You'd only need it if you weren't in the directory of the crate you were documenting

**Comment by steveklabnik** [comment]
I am marking this as easy because https://crates.io/crates/open should be able to do most of the work, I believe.
